import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  optimizeDeps: {
    include: [
      'echarts-gl',
    ],
  },
  build: {
      rollupOptions: {
        external: [
          // 添加你要 external 的模块名
          '数据新闻',
		        'src/assets/acordion/image1.png',
		        'src/assets/acordion/image2.png',
		        'src/assets/acordion/image3.png',
		        'src/assets/acordion/image4.png',
		        'src/assets/bounce/image1.png',
		        'src/assets/bounce/image2.png',
		        'src/assets/bounce/image3.png',
		        'src/assets/bounce/image4.png',
		        'src/assets/bounce/image5.png',
		        'src/assets/four/image1.png',
		        'src/assets/four/image2.png',
		        'src/assets/four/image3.png',
		        'src/assets/four/image4.png',
		        'src/assets/four/image5.png',
		        'src/assets/four/image6.png',
		        'src/assets/four/image7.png',
		        'src/assets/four/image8.png',
		        'src/assets/index/image1.png',
		        'src/assets/index/image2.png',
		        'src/assets/index/image3.png',
		        'src/assets/index/image4.png',
		        'src/assets/index/image5.png',
		        'src/assets/part1/image1.png',
		        'src/assets/part1/image2.png',
		        'src/assets/part1/image3.png',
		        'src/assets/part2/image1.png',
		        'src/assets/part2/image2.png',
		        'src/assets/part2/image3.png',
		        'src/assets/part2/image4.png',
		        'src/assets/part2/part2.png',
		        'src/assets/part3/image1.png',
		        'src/assets/part3/image2.png',
		        'src/assets/part3/image3.png',
		        'src/assets/part3/image4.png',
		        'src/assets/part3/image5.png',
		        'src/assets/part3/image6.png',
		        'src/assets/part3/image7.png',
		        'src/assets/part3/image8.png',
		        'src/assets/part3/image9.png',
		        'src/assets/part3/image10.png',
		        'src/assets/part3/image11.png',
		        'src/assets/part3/image12.png',
		        'src/assets/part3/part3.png',
		        'src/assets/part4/image1.png',
		        'src/assets/part4/image2.png',
		        'src/assets/part4/image3.png',
		        'src/assets/part4/image4.png',
		        'src/assets/part4/image5.png',
		        'src/assets/part4/image6.png',
		        'src/assets/part4/image7.png',
		        'src/assets/part4/part4.png',
		        'src/assets/part5/image1.png',
		        'src/assets/timeline/image1.png',
		        'src/assets/timeline/image2.png',
		        'src/assets/timeline/image3.png',
		        'src/assets/mail/im1.png',
		        'src/assets/mail/im2.png',
		        'src/assets/mail/im3.png',
		        'src/assets/mail/im4.png',
		        'src/assets/mail/im5.png',
		        'src/assets/mail/im6.png',
		        'src/assets/mail/im7.png',
		        'src/assets/mail/im8.png',
		        'src/assets/mail/im9.png',
		        'src/assets/mail/im10.png',
		        'src/assets/mail/im11.png',
		        'src/assets/mail/im12.png',
		        'src/assets/mail/im13.png',
		        'src/assets/mail/im14.png',
		        'src/assets/mail/im15.png',
		        'src/assets/mail/im16.png',
		        'src/assets/mail/im17.png',
		        'src/assets/mid-title/二级标题-1.png',
		        'src/assets/mid-title/二级标题-2.png',
		        'src/assets/mid-title/二级标题-3.png',
		        'src/assets/mid-title/二级标题-4.png',
		        'src/assets/mid-title/二级标题-5.png',
		        'src/assets/mid-title/二级标题-6.png',
		        'src/assets/mid-title/二级标题-7.png',
		        'src/assets/mid-title/二级标题-8.png',
		        'src/assets/mid-title/二级标题-9.png',
		        'src/assets/blindbox/card-back1.jpg',
		        'src/assets/blindbox/card-back2.jpg',
		        'src/assets/blindbox/card-back3.jpg',
		        'src/assets/blindbox/card-back4.jpg',
		        'src/assets/blindbox/card-back5.jpg',
		        'src/assets/blindbox/card-back6.jpg',
		        'src/assets/blindbox/card-face.png',
        ]
      }
    }
})


